server:
  port: 8888
  servlet:
    context-path: /

spring:
  datasource:
    hikari:
#      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      driver-class-name: org.mariadb.jdbc.Driver
#      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3337/test?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
      jdbc-url: jdbc:mariadb://localhost:3337/test?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: test
      password: test123!
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    host: localhost
    port: 6379

logging:
  config: classpath:log/logbak.xml

file:
  path:
    sample: d:/temp
    rest: d:/temp/rest

restInfo:
  url:
    local: http://localhost:8888